version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # ECR_URI에서 도메인 부분만 추출
      - ECR_REGISTRY=$(echo $ECR_URI | cut -d'/' -f1)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  pre_build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - FRONTEND_URI=$ECR_REGISTRY/$ACCOUNT-frontend:$IMAGE_TAG
      - BACKEND_URI=$ECR_REGISTRY/$ACCOUNT-backend:$IMAGE_TAG

  build:
    commands:
      - docker build -t $FRONTEND_URI ./frontend
      - docker build -t $BACKEND_URI ./backend

  post_build:
    commands:
      - docker push $FRONTEND_URI
      - docker push $BACKEND_URI
      - sed -i "s|IMAGE_TAG_PLACEHOLDER|$IMAGE_TAG|g" k8s/frontend-deployment.yaml
      - sed -i "s|IMAGE_TAG_PLACEHOLDER|$IMAGE_TAG|g" k8s/backend-deployment.yaml

artifacts:
  files:
    - k8s/**/*